spring:
  profiles:
    active: local
  jndi:
    ignore: true
  #国际化配置
  messages:
    encoding: utf-8
    defaultEncoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #thymeleaf配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #配置静态资源的位置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  # JavaMailSender 邮件发送的配置
  mail:
    host: smtp.qq.com
    #username: xxx@qq.com
    #password: password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cache:
    #cache-names: foo,bar,manager,role,node,personinfo,schedulejob
    #caffeine:
    #spec: initialCapacity=50,maximumSize=6000,expireAfterWrite=60s,refreshAfterWrite=10s
    redis:
      #缓存数据key是否使用前缀，默认是true
      use-key-prefix: false
      #redis中缓存超时的时间，默认60000ms
      time-to-live: 60000
      #是否缓存null数据，默认是false
      cache-null-values: false
    type: redis
  aop:
    #开启对AOP的支持
    auto: true
    #设置代理模式 true（cglib） false(java JDK代理)
    proxy-target-class: true
  output:
    ansi:
      #允许输出彩色日志
      enabled: always
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB

  #连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1                     #连接池初始大小
      max-active: 20                      #连接池中最大的活跃连接数
      min-idle: 1                         #连接池中最小的活跃连接数
      max-wait: 60000                     #配置获取连接等待超时的时间
      pool-prepared-statements: true    #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false             #是否在获得连接后检测其可用性
      test-on-return: false             #是否在连接放回连接池后检测其可用性
      test-while-idle: true             #是否在连接空闲一段时间后检测其可用性
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,slf4j #,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: true
        # 登录名
        #login-username: admin
        # 登录密码
        #login-password: 123456

server:
  compression:
    enabled: true
  tomcat:
    accept-count: 100
    max-connections: 2000
    max-threads: 500
    min-spare-threads: 50
    uri-encoding: UTF-8

#MyBatis
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.apollo.blog.entity,org.apollo.blog.models
  typeEnumsPackage: org.apollo.blog.entity.enums
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: IGNORED
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true

org:
  quartz:
    jobStore:
      #多实例QUARTZ出现重复执行
      acquireTriggersWithinLock: true