server:
  port: 8754
  servlet:
    context-path: /apollo
spring:
  mail:
    username: 1714167268@qq.com
    password: zcpxcynbbbxodcdg
  #连接池配置
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/apollo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
      # 配置DruidStatViewServlet
      stat-view-servlet:
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Green521388
    lettuce:
      pool:
        max-active:  200 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #连接超时时间
    timeout: 60000
    expire-time: 7200
    block-when-exhausted: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-local.xml

redisson:
  address: redis://127.0.0.1:6379
  password: Green521388

mybatis-plus:
  configuration:
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl